//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class MyWebSiteDatabaseEntities : DbContext
{
    public MyWebSiteDatabaseEntities()
        : base("name=MyWebSiteDatabaseEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<AnaBasliklar> AnaBasliklars { get; set; }
    public DbSet<PdfFile> PdfFiles { get; set; }
    public DbSet<VideoUrl> VideoUrls { get; set; }
    public DbSet<VideoYorumlari> VideoYorumlaris { get; set; }
    public DbSet<PdfYorumları> PdfYorumları { get; set; }
}
